# Generated by Django 3.1.3 on 2020-11-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201116_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='online',
            field=models.BooleanField(default=True),
        ),
    ]
